### PR TITLE
Basic build script

### PR DESCRIPTION
**Pull request by norswap**
This adds a basic Python script to build the optimism repository in Python and check the dependencies.

### CODE REVIEW

**Comment by GrapeBaBa** [comment]
Not written python project a long time, after some search, I think we can use https://github.com/pypa/sampleproject this project template to start, it use modern python build system and test lib. Also discover a new python linter/style check tools https://github.com/astral-sh/ruff which seems quite good to use.

**Comment by norswap** [comment]
I'm generally not in love with templates, they add a lot of cruft in a project, and they usually fail miserably at justifying why such or such components / tools are included.

I'd rather we introduce tools one by one once we have a good reason to use them.

We will need to settle on a tool for managing dependencies. Echoing discussions on our TG group I think we should either:
- use the builtin `venv` and `pip` with `python -m`
- use `poetry`

One thing I'd like to lookup in advance is the possibility to package the resulting script(s) in such a way that that does is very simple from the user perspective, i.e. probably we should only require having a semi-recent python3 installation for being able to run the scripts.

The current script fits the bill (as it doesn't have any dependencies instead of the modules shipping with python) — though it does use a relative include, so not sure it can be invoked from outside the repo without changing the directory to it first.

**Comment by GrapeBaBa** [comment]
> I'm generally not in love with templates, they add a lot of cruft in a project, and they usually fail miserably at justifying why such or such components / tools are included.
> 
> I'd rather we introduce tools one by one once we have a good reason to use them.
> 
> We will need to settle on a tool for managing dependencies. Echoing discussions on our TG group I think we should either:
> 
> * use the builtin `venv` and `pip` with `python -m`
> * use `poetry`
> 
> One thing I'd like to lookup in advance is the possibility to package the resulting script(s) in such a way that that does is very simple from the user perspective, i.e. probably we should only require having a semi-recent python3 installation for being able to run the scripts.
> 
> The current script fits the bill (as it doesn't have any dependencies instead of the modules shipping with python) — though it does use a relative include, so not sure it can be invoked from outside the repo without changing the directory to it first.

Yup, I also don't like introduce many libs/deps I don't know and I like to keep the code base clean. However I think for a good project structure, include a build tool(linter/style/formatter) and test lib is needed. I see that sample project not include too many deps, just add a pyproject.toml maybe enough. I actually prefer use the builtin `venv` and `pip` with `python -m` to keep it simple, I think it should not conflict with a pyproject file and add ruff for code style.

**Comment by GrapeBaBa** [comment]
I feel we can let this PR merged if others no comments, I can try to add a pyproject.toml in my local and check if it introduce more deps.

**Comment by norswap** [comment]
Yes, totally agree once we introduce dependencies (and thus chose a tool for that), we should also introduce a `pyproject.toml` file into the repo!

We can add one before, but are benefits when we don't have any dependencies yet?

**Pull request merged**
